const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImg'),lbCap=document.getElementById('lightboxCaption'),closeLbBtn=document.getElementById('closeLightbox');let lastLightboxTrigger=null;document.querySelectorAll('.work').forEach(btn=>btn.addEventListener('click',()=>{lastLightboxTrigger=btn;const caption=btn.dataset.caption||'';lbImg.src=btn.dataset.img;lbImg.alt=caption;lbCap.textContent=caption;lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';closeLbBtn.focus()}));function closeLb(){const wasOpen=lb.classList.contains('open');lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow='';if(wasOpen&&lastLightboxTrigger){lastLightboxTrigger.focus();lastLightboxTrigger=null}}closeLbBtn.onclick=closeLb;lb.addEventListener('click',e=>{if(e.target===lb)closeLb()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLb();closeMobileMenu()}if(e.key==='Tab'&&lb.classList.contains('open')){e.preventDefault();closeLbBtn.focus()}});const topBtn=document.getElementById('topBtn');window.addEventListener('scroll',()=>topBtn.classList.toggle('show',scrollY>700));
const mobileBtn=document.getElementById('mobileBtn'),mobileMenu=document.getElementById('mobileMenu'),siteHeader=document.getElementById('siteHeader');function setMobileMenu(open){mobileBtn.classList.toggle('open',open);mobileMenu.classList.toggle('open',open);mobileBtn.setAttribute('aria-expanded',String(open));mobileBtn.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');mobileMenu.setAttribute('aria-hidden',String(!open))}function closeMobileMenu(){setMobileMenu(false)}mobileBtn.addEventListener('click',e=>{e.stopPropagation();setMobileMenu(!mobileMenu.classList.contains('open'))});mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMobileMenu));document.addEventListener('click',e=>{if(mobileMenu.classList.contains('open')&&!siteHeader.contains(e.target))closeMobileMenu()});window.addEventListener('resize',()=>{if(innerWidth>980)closeMobileMenu()});
const progress=document.getElementById('scrollProgress');const navLinks=[...document.querySelectorAll('nav a[href^="#"]')];const navTargets=navLinks.map(link=>({link,section:document.querySelector(link.getAttribute('href'))})).filter(x=>x.section);const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function syncScrollEffects(){const max=document.documentElement.scrollHeight-innerHeight;const pct=max>0?Math.min(100,Math.max(0,scrollY/max*100)):0;progress.style.width=pct+'%';let current='';navTargets.forEach(({section})=>{if(section.getBoundingClientRect().top<=innerHeight*.42)current='#'+section.id});navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===current));if(!reduceMotion&&innerWidth>640){const hero=document.querySelector('.hero');hero.style.setProperty('--hero-shift',Math.min(scrollY*.06,34)+'px')}}window.addEventListener('scroll',syncScrollEffects,{passive:true});window.addEventListener('resize',syncScrollEffects);syncScrollEffects();
// Google reviews API kept on standby: no key configured, no billable calls.
// HEADER_FLUTUANTE_JS
const persistentHeader=document.getElementById('siteHeader');const syncPersistentHeader=()=>{if(persistentHeader)persistentHeader.classList.toggle('scrolled',window.scrollY>36)};window.addEventListener('scroll',syncPersistentHeader,{passive:true});syncPersistentHeader();

// ORCAMENTO_INTELIGENTE_JS
const quoteForm=document.getElementById('quoteForm');if(quoteForm){quoteForm.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('quoteName').value.trim();const city=document.getElementById('quoteCity').value.trim();const service=document.getElementById('quoteService').value;const details=document.getElementById('quoteDetails').value.trim();if(!name||!city||!service){quoteForm.reportValidity();return}const lines=['Olá! Vim pelo site da Help Eletro e gostaria de solicitar um orçamento.','','Nome: '+name,'Cidade: '+city,'Serviço: '+service];if(details)lines.push('Detalhes: '+details);const url='https://wa.me/5519997287304?text='+encodeURIComponent(lines.join('\n'));window.open(url,'_blank','noopener,noreferrer')})}
// ORCAMENTO_V1_PUBLICADO


// ANALYTICS_EVENTOS_PREPARADOS
// Os eventos abaixo passam a ser enviados automaticamente quando o Google Analytics (gtag) for configurado.
function trackHelpEvent(eventName,params={}){if(typeof window.gtag==='function'){window.gtag('event',eventName,params)}}
document.addEventListener('click',e=>{const link=e.target.closest('a');if(!link)return;const href=link.getAttribute('href')||'';if(href.includes('wa.me')){trackHelpEvent('whatsapp_click',{link_text:(link.textContent||'').trim()})}else if(href.includes('instagram.com')){trackHelpEvent('instagram_click',{link_text:(link.textContent||'').trim()})}else if(href.includes('share.google')){trackHelpEvent('google_reviews_click',{link_text:(link.textContent||'').trim()})}});
if(quoteForm){quoteForm.addEventListener('submit',()=>trackHelpEvent('quote_form_submit',{service:document.getElementById('quoteService')?.value||''}))}

// ANALYTICS_CONSENTIMENTO
// Google Analytics 4 (G-REFQPZ3DHW) só é carregado depois que o visitante aceita os cookies.
const GA_ID='G-REFQPZ3DHW',CONSENT_KEY='helpCookieConsent';const cookieBanner=document.getElementById('cookieBanner');let gaLoaded=false;
function readConsent(){try{return localStorage.getItem(CONSENT_KEY)}catch(e){return null}}function saveConsent(value){try{localStorage.setItem(CONSENT_KEY,value)}catch(e){}}
function loadAnalytics(){window['ga-disable-'+GA_ID]=false;if(gaLoaded){window.gtag('consent','update',{analytics_storage:'granted'});return}gaLoaded=true;window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('consent','default',{analytics_storage:'granted',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});window.gtag('js',new Date());window.gtag('config',GA_ID);const gaScript=document.createElement('script');gaScript.async=true;gaScript.src='https://www.googletagmanager.com/gtag/js?id='+GA_ID;document.head.appendChild(gaScript)}
function disableAnalytics(){window['ga-disable-'+GA_ID]=true;if(gaLoaded)window.gtag('consent','update',{analytics_storage:'denied'});document.cookie.split(';').map(c=>c.split('=')[0].trim()).filter(n=>n==='_ga'||n.startsWith('_ga_')).forEach(n=>{document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=.'+location.hostname.replace(/^www\./,'')})}
function setCookieBanner(show){if(cookieBanner)cookieBanner.hidden=!show}
if(cookieBanner){const consent=readConsent();if(consent==='accepted')loadAnalytics();else if(consent!=='rejected')setCookieBanner(true);document.getElementById('cookieAccept').addEventListener('click',()=>{saveConsent('accepted');loadAnalytics();setCookieBanner(false)});document.getElementById('cookieReject').addEventListener('click',()=>{saveConsent('rejected');disableAnalytics();setCookieBanner(false)});document.getElementById('cookiePrefs').addEventListener('click',()=>{setCookieBanner(true);document.getElementById('cookieAccept').focus()})}
