const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImg'),lbCap=document.getElementById('lightboxCaption');document.querySelectorAll('.work').forEach(btn=>btn.addEventListener('click',()=>{lbImg.src=btn.dataset.img;lbCap.textContent=btn.dataset.caption||'';lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));function closeLb(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.getElementById('closeLightbox').onclick=closeLb;lb.addEventListener('click',e=>{if(e.target===lb)closeLb()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLb();closeMobileMenu()}});const topBtn=document.getElementById('topBtn');window.addEventListener('scroll',()=>topBtn.classList.toggle('show',scrollY>700));
const mobileBtn=document.getElementById('mobileBtn'),mobileMenu=document.getElementById('mobileMenu'),siteHeader=document.getElementById('siteHeader');function setMobileMenu(open){mobileBtn.classList.toggle('open',open);mobileMenu.classList.toggle('open',open);mobileBtn.setAttribute('aria-expanded',String(open));mobileBtn.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');mobileMenu.setAttribute('aria-hidden',String(!open))}function closeMobileMenu(){setMobileMenu(false)}mobileBtn.addEventListener('click',e=>{e.stopPropagation();setMobileMenu(!mobileMenu.classList.contains('open'))});mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMobileMenu));document.addEventListener('click',e=>{if(mobileMenu.classList.contains('open')&&!siteHeader.contains(e.target))closeMobileMenu()});window.addEventListener('resize',()=>{if(innerWidth>980)closeMobileMenu()});
const progress=document.getElementById('scrollProgress');const navLinks=[...document.querySelectorAll('nav a[href^="#"]')];const navTargets=navLinks.map(link=>({link,section:document.querySelector(link.getAttribute('href'))})).filter(x=>x.section);const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function syncScrollEffects(){const max=document.documentElement.scrollHeight-innerHeight;const pct=max>0?Math.min(100,Math.max(0,scrollY/max*100)):0;progress.style.width=pct+'%';let current='';navTargets.forEach(({section})=>{if(section.getBoundingClientRect().top<=innerHeight*.42)current='#'+section.id});navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===current));if(!reduceMotion&&innerWidth>640){const hero=document.querySelector('.hero');hero.style.setProperty('--hero-shift',Math.min(scrollY*.06,34)+'px')}}window.addEventListener('scroll',syncScrollEffects,{passive:true});window.addEventListener('resize',syncScrollEffects);syncScrollEffects();
// Google reviews API kept on standby: no key configured, no billable calls.
// HEADER_FLUTUANTE_JS
const persistentHeader=document.getElementById('siteHeader');const syncPersistentHeader=()=>{if(persistentHeader)persistentHeader.classList.toggle('scrolled',window.scrollY>36)};window.addEventListener('scroll',syncPersistentHeader,{passive:true});syncPersistentHeader();

// ORCAMENTO_INTELIGENTE_JS
const quoteForm=document.getElementById('quoteForm');if(quoteForm){quoteForm.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('quoteName').value.trim();const city=document.getElementById('quoteCity').value.trim();const service=document.getElementById('quoteService').value;const details=document.getElementById('quoteDetails').value.trim();if(!name||!city||!service){quoteForm.reportValidity();return}const lines=['Olá! Vim pelo site da Help Eletro e gostaria de solicitar um orçamento.','','Nome: '+name,'Cidade: '+city,'Serviço: '+service];if(details)lines.push('Detalhes: '+details);const url='https://wa.me/5519997287304?text='+encodeURIComponent(lines.join('\n'));window.open(url,'_blank','noopener,noreferrer')})}
// ORCAMENTO_V1_PUBLICADO


// ANALYTICS_EVENTOS_PREPARADOS
// Os eventos abaixo passam a ser enviados automaticamente quando o Google Analytics (gtag) for configurado.
function trackHelpEvent(eventName,params={}){if(typeof window.gtag==='function'){window.gtag('event',eventName,params)}}
document.addEventListener('click',e=>{const link=e.target.closest('a');if(!link)return;const href=link.getAttribute('href')||'';if(href.includes('wa.me')){trackHelpEvent('whatsapp_click',{link_text:(link.textContent||'').trim()})}else if(href.includes('instagram.com')){trackHelpEvent('instagram_click',{link_text:(link.textContent||'').trim()})}else if(href.includes('share.google')){trackHelpEvent('google_reviews_click',{link_text:(link.textContent||'').trim()})}});
if(quoteForm){quoteForm.addEventListener('submit',()=>trackHelpEvent('quote_form_submit',{service:document.getElementById('quoteService')?.value||''}))}
